name: Build latest and upload
on:
  push:
    branches:
      - main
      - add-build-pipeline
jobs:
  build:
    name: Building latest code and uploading dist
    runs-on: windows-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2

      - name: Install ncc
        run: npm i -g @vercel/ncc

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build
      
      - name: Commit latest dist folder to repository
        uses: EndBug/add-and-commit@v7
        with:
          add: 'dist'
          push: true
      